name: Deploy Next.js to Azure Container Registry

on:
  push:
    branches:
      - main  # deploy when pushing to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/hacknova-web:latest .

    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/hacknova-web:latest
